name: main

on:
  # pull_request:
  #   types:
  #   - closed
  #   branches:
  #   - main
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: write
  issues: write
  
# concurrency:
#   group: ${{ github.ref }}  # Unique group for each branch or PR
#   cancel-in-progress: true   # Cancel in-progress runs of the same group

jobs:
  build:
    if: github.event_name != 'pull_request'
    secrets: inherit
    needs:
    - build
    uses: coursebox-ai/coursebox-action@v1
    with:
      project: coursebox-ai-dev
      project_number: 214599382085