name: main

on:
  # pull_request:
  #   types:
  #   - closed
  #   branches:
  #   - main
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read
  issues: write
  
# concurrency:
#   group: ${{ github.ref }}  # Unique group for each branch or PR
#   cancel-in-progress: true   # Cancel in-progress runs of the same group

jobs:
  build:
    name: build and deploy
    if: github.event_name != 'pull_request'
    # secrets: inherit
    
    runs-on: ubuntu-latest  # ✅ Required for job execution environment

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Use shallow clone to only send this branch
      - name: build and deploy
        uses: Coursebox-ai/coursebox-action@v1
        with:
          project: coursebox-ai-dev
          project_number: 214599382085