name: main

on:
  # pull_request:
  #   types:
  #   - closed
  #   branches:
  #   - main
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: write
  issues: write
  
# concurrency:
#   group: ${{ github.ref }}  # Unique group for each branch or PR
#   cancel-in-progress: true   # Cancel in-progress runs of the same group

jobs:
  build:
    if: github.event_name != 'pull_request'
    secrets: inherit
    
    runs-on: ubuntu-latest  # ✅ Required for job execution environment

    steps:
      - name: build and deploy
        uses: Coursebox-ai/coursebox-action@main
        with:
          project: coursebox-ai-dev
          project_number: 214599382085